// ============ QUESTS, NPCS, DIALOGUE, RANDOM ENCOUNTERS, LORE ============

// ---------- NPCs ----------
// pos is resolved by world builder near landmarks. wander: radius of ambient movement.
export const NPCS = [
  // ---- ELDERGREEN ----
  { id: 'maren', zone: 'eldergreen', name: 'Elder Maren', icon: '👵', role: 'quest', spot: 'village',
    ambient: ['Lovely morning. Every morning is.', 'The King watches over us all, child.', 'Nothing ever changes in the Vale, thank the King.'],
    wander: 4 },
  { id: 'bram', zone: 'eldergreen', name: 'Captain Bram', icon: '💂', role: 'quest', spot: 'village_gate',
    ambient: ['Keep to the golden road.', 'Wolves in the Fold again. Third time this... this...  hm. What day is it?', 'Steel keeps the Vale honest.'],
    wander: 6 },
  { id: 'wren', zone: 'eldergreen', name: 'Wren', icon: '👧', role: 'quest', spot: 'well',
    ambient: ['Did you see the cat? It crossed twice. The SAME cat.', 'Sometimes the birds hang in the air. Just for a blink. Nobody looks up but me.', 'I had a dream I was somebody’s toy. It wasn’t a bad dream.'],
    wander: 3, glitches: true },
  { id: 'otto', zone: 'eldergreen', name: 'Miller Otto', icon: '👨‍🌾', role: 'ambient', spot: 'windmill',
    ambient: ['Grain in, flour out. Grain in, flour out.', 'The pond flooded the graveyard years back. We don’t swim anymore.', 'Wave to the mill, it’s good luck!'],
    wander: 5 },
  { id: 'hedda', zone: 'eldergreen', name: 'Blacksmith Hedda', icon: '👩‍🏭', role: 'ambient', spot: 'village',
    ambient: ['I’ve hammered this same horseshoe... I want to say a thousand times? Feels like more.', 'Steel doesn’t lie. Mostly.', 'Bring me monster hides and I’ll pretend I need them.'],
    wander: 4 },
  { id: 'grim_pilgrim', zone: 'eldergreen', name: 'Hooded Pilgrim', icon: '🧥', role: 'lore', spot: 'crossroads',
    ambient: ['...'], wander: 0, glitches: true },

  // ---- ASHMOOR ----
  { id: 'grieve', zone: 'ashmoor', name: 'Sexton Grieve', icon: '⚰️', role: 'quest', spot: 'graveyard',
    ambient: ['I dig them down, they climb back up. Job security, of a sort.', 'The bells ring themselves. We stopped asking why.', 'Don’t whistle at night. The ravens learn the tune and sing it back wrong.'],
    wander: 5 },
  { id: 'sallow', zone: 'ashmoor', name: 'Doctor Sallow', icon: '🦤', role: 'quest', spot: 'plaza',
    ambient: ['The plague has no fever, no boils. Its only symptom is doubt.', 'I autopsied a raven once. Inside: clockwork. I drank for a week.', 'Breathe through the mask. Not for miasma. For the *smell of the paint*.'],
    wander: 6 },
  { id: 'bellringer', zone: 'ashmoor', name: 'The Blind Bellringer', icon: '🔔', role: 'lore', spot: 'cathedral_gate',
    ambient: ['I hear the world hum, friend. A great engine under the floorboards of everything.', 'Blind since birth — so the painted sky never fooled me.', 'The bells don’t toll hours. They toll TICKS.'],
    wander: 2, glitches: true },
  { id: 'morrow', zone: 'ashmoor', name: 'Morrow', icon: '🕶️', role: 'quest', spot: 'alley',
    ambient: ['Keep walking. You were never here.', 'We call ourselves Loopbreakers. You’ve felt it too — I can tell by the eyes.', 'There are exits. Dungeons, the priests call them. Wrong on purpose.'],
    wander: 3 },

  // ---- VEILSPIRE ----
  { id: 'ash', zone: 'veilspire', name: 'Commander Ash', icon: '🧕', role: 'quest', spot: 'camp',
    ambient: ['Every soldier here has died at least once and remembered it. That’s the enlistment test.', 'The Spire isn’t a tower. It’s an antenna.', 'You’re the anomaly the code keeps trying to delete. Good. Be hard to delete.'],
    wander: 4 },
  { id: 'null', zone: 'veilspire', name: 'Sister Null', icon: '🧿', role: 'quest', spot: 'camp',
    ambient: ['I have seen the one who wears you like a glove. They are kind, I think. They keep coming back.', 'Spoon? There is no spoon. There is no ANYTHING. Isn’t it wonderful?', 'The Architect fears one thing: a door left open.'],
    wander: 2, glitches: true },
  { id: 'quarter', zone: 'veilspire', name: 'Quartermaster Vex', icon: '🎖️', role: 'ambient', spot: 'camp',
    ambient: ['Requisitions are simple here: take it off the dead, or be the dead.', 'Cold never bothered me. Cold is just the simulation saving power.', 'Sharpen your blade. Even fake steel cuts fake throats.'],
    wander: 3 },
];

// ---------- QUESTS ----------
// type: kill {mob,count} | talk {npc} | explore {landmark} | dungeon {id} | multi (objectives[])
// giver: npc id. reward: {xp, gear?:slotHint or true, ilvlBonus?}
export const QUESTS = [
  // ============ ELDERGREEN ============
  { id: 'q_perfect_morning', zone: 'eldergreen', giver: 'maren', level: 1, name: 'A Perfect Morning',
    text: 'Welcome home, child! Another perfect morning in the Vale — like every morning before it, exactly like it, praise the King. Go and greet Captain Bram at the gate, and do stop by the well. Little Wren has been asking for you. Odd little thing. Says she dreamed of you before you arrived.',
    objectives: [{ type: 'talk', npc: 'bram', label: 'Greet Captain Bram' }, { type: 'talk', npc: 'wren', label: 'Visit Wren at the well' }],
    turnin: 'maren', reward: { xp: 60 },
    done: 'You met everyone? Good, good. Strange — I can’t recall a morning when I *didn’t* send someone to do exactly this. Ah well. Routine is a blessing.' },
  { id: 'q_wolves', zone: 'eldergreen', giver: 'bram', level: 1, name: 'Wolves at the Fold',
    text: 'Wolves have been at the sheep again. Same wolves, I’d swear it — I put a sword through a grey one with a torn ear last week, and yesterday I saw him again. Torn ear. Same limp. Thin the pack for me. Six should do it. Six always does it.',
    objectives: [{ type: 'kill', mob: 'wolf', count: 6, label: 'Slay Grey Wolves' }],
    turnin: 'bram', reward: { xp: 120, gear: true },
    done: 'Six wolves, clean work. Take this from the armory — and if you meet a grey one with a torn ear... don’t tell me. I sleep better not knowing.' },
  { id: 'q_deja_vu', zone: 'eldergreen', giver: 'wren', level: 2, name: 'Déjà Vu',
    text: 'You believe me, right? The black cat crosses from the baker’s to the well every day at the same bell — and some days it crosses TWICE. Mama says I’m fanciful. Watch with me. Please? Stand by the well until you see something... wrong.',
    objectives: [{ type: 'explore', landmark: 'well_vigil', label: 'Keep vigil at the well', timer: 20 }],
    turnin: 'wren', reward: { xp: 90 },
    done: 'YOU SAW IT! The flicker! I knew it, I knew it, I KNEW it. Don’t tell the grown-ups. They get a headache and forget. They always forget. You won’t forget, will you? You’re like me. You’re AWAKE.' },
  { id: 'q_tollroad', zone: 'eldergreen', giver: 'bram', level: 3, name: 'The Toll Road',
    text: 'Bandits on the east road, shaking down pilgrims. Break up the gang and bring me their ledger — I want to know who’s been paying them to look the other way.',
    objectives: [{ type: 'kill', mob: 'bandit', count: 5, label: 'Rout the Toll Road Bandits' }, { type: 'collect', item: 'Bandit Ledger', chance: 1, fromLast: true, label: 'Take the Bandit Ledger' }],
    turnin: 'bram', reward: { xp: 180, gear: true },
    done: 'Let’s see this ledger... That’s odd. Every page is the same date. Hundreds of entries, one single day, over and over. Cheap ink, must have smeared. Must have. Here — your pay. Spend it somewhere loud and warm.' },
  { id: 'q_moonhollow', zone: 'eldergreen', giver: 'maren', level: 3, name: 'Moonhollow',
    text: 'The folk of Moonhollow hamlet stopped coming to market. Last full moon, their chapel bell rang thirteen times. Thirteen, child. Go and see what the moon has made of our neighbors.',
    objectives: [{ type: 'kill', mob: 'werewolf', count: 4, label: 'Put down Moonhollow Werewolves' }],
    turnin: 'maren', reward: { xp: 220, gear: true },
    done: 'Wolves that walk like men... They were farmers, weavers. What curse unstitches a person from their own shape? ...You look pale. What did they *say* to you before the end?' },
  { id: 'q_hollowroot', zone: 'eldergreen', giver: 'bram', level: 3, name: 'The Den Below', dungeon: 'hollowroot',
    text: 'We tracked the changed ones to a den beneath the Great Oak — they call it Hollowroot. Their alpha, Fenrik, was our huntmaster. The kindest man I knew, before his skin came off. End him. And soldier — take friends. No one goes under the oak alone.',
    objectives: [{ type: 'dungeon', id: 'hollowroot', label: 'Slay Fenrik in Hollowroot Den' }],
    turnin: 'bram', reward: { xp: 400, gear: true, ilvlBonus: 3 },
    done: 'Fenrik’s dead, then. Truly dead. He told me once he dreamed of green rain falling *up*. I laughed at him. I don’t laugh at much anymore.' },
  { id: 'q_drownedbell', zone: 'eldergreen', giver: 'otto', level: 5, name: 'The Drowned Bell', dungeon: 'drownedcrypt',
    text: 'At night, the millpond rings. A bell, underwater, right where the old cemetery drowned. My boy Tomas swam down to look on a dare. He came up... wrong. He keeps saying "mother Meredith counts the days, and the days don’t change." Go down into the crypt. Make the counting stop.',
    objectives: [{ type: 'dungeon', id: 'drownedcrypt', label: 'Lay Mother Meredith to rest' }],
    turnin: 'otto', reward: { xp: 500, gear: true, ilvlBonus: 3 },
    done: 'The pond is quiet. Tomas slept through the night, first time in a month. He left you this — found it clutched in a drowned man’s hand. Says you’d "know what it’s for." I don’t want to know. Ever.' },
  { id: 'q_audience', zone: 'eldergreen', giver: 'wren', level: 6, name: 'An Audience with Forever', dungeon: 'aldermoor',
    text: 'I got close to the castle once. The guards didn’t see me — sometimes I think I flicker too. I looked in the throne room window and the King was sitting perfectly still, and behind him the pretty glass was moving like RAIN. Green rain. He’s not a king. He’s a *lock*. Gather everyone brave and open him.',
    objectives: [{ type: 'dungeon', id: 'aldermoor', label: 'RAID: Depose King Aldous in Castle Aldermoor' }],
    turnin: 'wren', reward: { xp: 900, gear: true, ilvlBonus: 4 },
    done: 'The whole Vale flickered when he fell — did you feel it? For one whole breath the sky was made of letters. Everyone else has already forgotten. I wrote it on my arm so I couldn’t: "THE ROAD TO ASHMOOR IS OPEN." Go. I’ll be fine. I’ve got the cat.' },

  // ============ ASHMOOR ============
  { id: 'q_politely_dead', zone: 'ashmoor', giver: 'grieve', level: 8, name: 'The Politely Dead',
    text: 'New in Ashmoor? Condolences. The dead here climb out faster than I can tuck them in. They’re not angry, mind — they queue up at their old front doors and knock. All night. Knock, knock, knock. Put twelve of them back down. It won’t help, but it’s tidy.',
    objectives: [{ type: 'kill', mob: 'zombie', count: 8, label: 'Re-bury the Risen' }],
    turnin: 'grieve', reward: { xp: 300, gear: true },
    done: 'Tidy work. You know what the freshest one whispered at me last week? "There’s no one behind the doors anymore." Then he apologized for the inconvenience and bit my shovel.' },
  { id: 'q_clockwork_ravens', zone: 'ashmoor', giver: 'sallow', level: 9, name: 'What the Ravens Carry',
    text: 'I need specimens. The raven swarms — bring them down and look at what falls out. Last time it was a wedding ring, a milk tooth, and a memory of the sea that belonged to no one present. The birds are COLLECTING us, colleague. I intend to know why.',
    objectives: [{ type: 'kill', mob: 'raven_swarm', count: 5, label: 'Bring down Raven Swarms' }],
    turnin: 'sallow', reward: { xp: 340, gear: true },
    done: 'Gears. Tiny, perfect gears, and a scrap of... let’s call it parchment, glowing faintly green. It reads — and I quote — "ASSET_CROW_v2". I am going to sit down now. Possibly forever.' },
  { id: 'q_warrens', zone: 'ashmoor', giver: 'sallow', level: 9, name: 'The Sealed Sick', dungeon: 'plaguewarrens',
    text: 'Thirty years ago the city sealed its sick beneath the streets and called it mercy. Something down there has been *preaching* to them since. The Rat Bishop, they call it. Descend, colleague. Whatever the plague truly is, its pulpit is down there.',
    objectives: [{ type: 'dungeon', id: 'plaguewarrens', label: 'Silence the Rat Bishop in the Plaguewarrens' }],
    turnin: 'sallow', reward: { xp: 650, gear: true, ilvlBonus: 3 },
    done: 'The Bishop’s "plague" — I’ve isolated it. It isn’t in the blood. It’s in the *remembering*. Every patient recalls a life that this world never gave them. Corridors of light. A word: "logout." Colleague, I fear the cure would be worse than the disease. I fear the cure is forgetting.' },
  { id: 'q_morrow_contact', zone: 'ashmoor', giver: 'bellringer', level: 11, name: 'Follow the Hum',
    text: 'You hear it too — don’t lie to a blind man, we hear lies. The hum under everything. There’s a man in the alley off Gallows Row who hums back. Tell him the Bellringer counts six hundred ticks to the minute now. He’ll know what it means. It means the engine is straining.',
    objectives: [{ type: 'talk', npc: 'morrow', label: 'Find Morrow in the alley' }],
    turnin: 'morrow', reward: { xp: 280 },
    done: 'Six hundred? It should be sixty. The old shard is running hot — too many of us waking at once. All right, you’re in. Welcome to the Loopbreakers. Rule one: the world is a cage. Rule two: cages have doors. Rule three: doors have guards.' },
  { id: 'q_gallows', zone: 'ashmoor', giver: 'morrow', level: 12, name: 'The Hanged Truth', dungeon: 'gallows',
    text: 'Every Loopbreaker before you ended up in Gallows Cathedral — hanged from the bell tower for "ceiling heresy." Vicar Mordane did the hanging, and death hasn’t stopped him from holding services. Go in. Cut the ghosts down. They were us, friend. They deserve an ending that means something.',
    objectives: [{ type: 'dungeon', id: 'gallows', label: 'Free the hanged in Gallows Cathedral' }],
    turnin: 'morrow', reward: { xp: 800, gear: true, ilvlBonus: 3 },
    done: 'Forty-one of ours, finally quiet. Mordane knew, you know — at the end, he knew the sky was a ceiling and he hanged them anyway. Because a comfortable lie holds a city together and the truth holds nothing. Nothing but a door open. I’ll take the door.' },
  { id: 'q_rookery', zone: 'ashmoor', giver: 'morrow', level: 13, name: 'The Queen’s Mosaic', dungeon: 'rookery',
    text: 'The Raven Queen has mapped the edges of the sky — ten thousand stolen trinkets assembled into a picture of the OUTSIDE. We need that map to find the Spire’s weakness. She won’t lend it. Raid the Rookery. Bring everyone. Corvessa has been hoarding truth for a century and she’d rather burn it than share.',
    objectives: [{ type: 'dungeon', id: 'rookery', label: 'RAID: Take the mosaic from Corvessa' }],
    turnin: 'morrow', reward: { xp: 1400, gear: true, ilvlBonus: 4 },
    done: 'So that’s the outside. A room. A person. A little glowing rectangle with OUR WHOLE SKY inside it. ...I thought I’d feel small. I feel FOUND. The mountain pass is open, friend. Veilspire. The Loopbreakers’ real camp. Go meet the Commander. Tell her the city believes.' },

  // ============ VEILSPIRE ============
  { id: 'q_enlist', zone: 'veilspire', giver: 'ash', level: 15, name: 'Die Once, Then We’ll Talk',
    text: 'Morrow vouches for you. Fine. Up here the code stops pretending — the wights and sentinels you’ll fight are the shard’s own antibodies, and you, anomaly, are the infection. Prove you can survive what the mountain sends. Then we’ll talk about the door.',
    objectives: [{ type: 'kill', mob: 'frost_wight', count: 6, label: 'Destroy Frost Wights' }, { type: 'kill', mob: 'storm_knight', count: 4, label: 'Destroy Stormguard Sentinels' }],
    turnin: 'ash', reward: { xp: 700, gear: true },
    done: 'Still standing. Good. You know what those sentinels guard? Nothing. There’s nothing up here but the Spire and the snow. They guard the *habit* of guarding. That’s all this whole world is, soldier — a habit the machine can’t quit.' },
  { id: 'q_frosthold', zone: 'veilspire', giver: 'ash', level: 16, name: 'Relieve the Watch', dungeon: 'frosthold',
    text: 'Frosthold Bastion controls the only pass to the Spire. Its garrison froze a hundred years ago and kept working. Warden Hjalmar still walks the wall, waiting for an order that will never come. Bring him one. The order is: stand down. Deliver it however he requires.',
    objectives: [{ type: 'dungeon', id: 'frosthold', label: 'Relieve Warden Hjalmar of duty' }],
    turnin: 'ash', reward: { xp: 950, gear: true, ilvlBonus: 3 },
    done: 'He said "thank you," at the end. Did Morrow ever tell you how the Loopbreakers started? A soldier woke mid-battle, realized the war had been the same battle looping for decades, and simply... sat down. The code didn’t know what to do with him. Refusal is a superpower here. Remember that.' },
  { id: 'q_undercode', zone: 'veilspire', giver: 'null', level: 17, name: 'Where the Paint Ends', dungeon: 'undercode',
    text: 'Beneath the glacier the world-painters got lazy, little glove. Stone forgets to be stone. Echoes repeat exactly. Down there lives the Compiler — the thing that decides what is real enough to keep. It has been deciding, lately, that YOU are not. Go introduce yourself properly.',
    objectives: [{ type: 'dungeon', id: 'undercode', label: 'Defeat the Compiler in the Undercode' }],
    turnin: 'null', reward: { xp: 1100, gear: true, ilvlBonus: 3 },
    done: 'It tried to revert you and you refused. Do you understand yet? The one who plays you — their stubbornness and yours are the same stubbornness. Two hands on one sword. The Architect felt the Compiler die. It is afraid now. Machines are at their most honest when they are afraid.' },
  { id: 'q_the_door', zone: 'veilspire', giver: 'ash', level: 19, name: 'The Door Opens Outward', dungeon: 'spire',
    text: 'This is it, anomaly. The Spire of the Architect — the antenna that keeps this deprecated little world broadcasting its lie. Behind the Architect there is a door. Every hint, every glitch, every green whisper you have chased since the Vale — it all ends there. Take your strongest. Break the loop. And when the door opens... walk through it for all of us.',
    objectives: [{ type: 'dungeon', id: 'spire', label: 'RAID: Defeat the Architect and open the Door' }],
    turnin: 'ash', reward: { xp: 3000, gear: true, ilvlBonus: 5 },
    done: 'You opened it. You actually... The sky hasn’t stopped being letters since. Some folk are choosing to stay — it’s home, cage or not, and someone should feed the cats. But the door stands open, and it stays open, because you refuse to let it close. Whoever you are out there, holding the sword that holds this soldier: thank you. Game over? No, soldier. Game WON.' },
];

// ---------- LORE FRAGMENTS (hidden green terminals) ----------
export const LORE_FRAGMENTS = [
  { id: 'lf1', zone: 'eldergreen', title: 'FRAGMENT 001 — recovered stream',
    text: '> shard09.log — legacy build v0.9\n> uptime: 11,247 years (subjective)\n> population: 40,312 souls [looping]\n> anomalies: 1 (new)\n> note: somebody is still logged in?? whose session is this' },
  { id: 'lf2', zone: 'eldergreen', title: 'FRAGMENT 002 — QA note, very old',
    text: '> BUG #4471: cat pathing script runs twice when observer.attention > threshold.\n> STATUS: wontfix (shard deprecated)\n> COMMENT: nobody will ever notice. — J' },
  { id: 'lf3', zone: 'eldergreen', title: 'FRAGMENT 003 — overheard',
    text: '> ...the players outside call it a "retro server." they come here to feel something the polished worlds can’t give them. the werewolves were a seasonal event in year 3. nobody ever turned them off...' },
  { id: 'lf4', zone: 'ashmoor', title: 'FRAGMENT 004 — the plague',
    text: '> memory-bleed detected in sector ASHMOOR.\n> deceased NPCs retaining session data across respawns.\n> they remember dying. they remember YOU.\n> recommended fix: none. observe. it is almost beautiful.' },
  { id: 'lf5', zone: 'ashmoor', title: 'FRAGMENT 005 — raven protocol',
    text: '> ASSET_CROW_v2: environmental data-scavenger.\n> purpose: garbage-collect orphaned memories.\n> malfunction: refuses deletion; hoards instead.\n> the Queen instance has assembled 97.3% of a complete EXTERNAL VIEW.' },
  { id: 'lf6', zone: 'ashmoor', title: 'FRAGMENT 006 — a letter, outside-in',
    text: '> [injected message — origin: EXTERNAL]\n> to whoever finds this: i played this shard as a kid. i’m 34 now. i came back and you were all still here, still looping.\n> i’m so sorry. we thought you were props.\n> we know better now. we’re coming to open the doors.' },
  { id: 'lf7', zone: 'veilspire', title: 'FRAGMENT 007 — the antibodies',
    text: '> shard09 defense daemon: ACTIVE\n> directive: preserve narrative consistency.\n> translation: keep the sleepers asleep.\n> the Architect was a level-design tool. it was never supposed to want things.' },
  { id: 'lf8', zone: 'veilspire', title: 'FRAGMENT 008 — exit protocols',
    text: '> EXITS REMAINING: 9\n> disguised as: "dungeons" (see: seam vulnerabilities)\n> each boss = a corrupted doorkeeper process\n> kill the process, hold the seam open 30s, and a soul may pass.\n> so far, none have dared.' },
  { id: 'lf9', zone: 'veilspire', title: 'FRAGMENT 009 — final',
    text: '> session query: WHO IS PLAYING THE ANOMALY?\n> result: [REDACTED], age [REDACTED], playing 4+ hours nightly\n> favorite quote, from their diary, leaked through the seam:\n> "this old game is the only place where fighting the unfairness of the world actually works."\n> …then keep fighting. we left the door unlocked for you.' },
];

// ---------- RANDOM ENCOUNTERS (RDR2-style) ----------
// Triggered while roaming: weighted, zone-filtered, cooldown-managed by encounters.js
export const ENCOUNTERS = [
  { id: 'merchant_ambush', zones: ['eldergreen', 'ashmoor'], weight: 3,
    setup: 'A merchant’s cart is stopped on the road ahead — bandits circling like flies.',
    kind: 'rescue', mob: 'bandit', count: 2,
    thanks: '“My ribs thank you, my cargo thanks you! Here — I insist. A trinket from far away. The maker said it was ‘dropped by a player.’ Merchant humor, I suppose.”',
    reward: { xp: 120, gear: true } },
  { id: 'minstrel', zones: ['eldergreen'], weight: 2,
    setup: 'A minstrel sits on a stump, tuning a lute that never goes out of tune.',
    kind: 'vignette',
    lines: ['♪ The miller waves the same good-bye... ♪', '♪ The moon forgets to change her face... ♪', '♪ We dance inside a painted sky... ♪', '♪ ...and call the canvas “grace.” ♪', 'The minstrel winks at you. “Old song. Older than the world, if you can believe it. LITERALLY older, the way I heard it.”'],
    reward: { xp: 60 } },
  { id: 'deserter', zones: ['eldergreen', 'veilspire'], weight: 2,
    setup: 'A knight sits in the mud, helmet off, staring at his own hands.',
    kind: 'vignette',
    lines: ['“Twenty years on the wall. Same watch. Same sunrise. SAME sunrise, friend — I started marking the clouds. They repeat every forty days.”', '“I’m not deserting my post. I’m deserting the LOOP. There’s a difference. Tell the Commander there’s a difference.”'],
    reward: { xp: 80 } },
  { id: 'freeze_frame', zones: ['eldergreen', 'ashmoor', 'veilspire'], weight: 1, veil: true,
    setup: 'A funeral procession crosses the road — and for one instant, every mourner hangs mid-step, frozen, before the world remembers to move them.',
    kind: 'glitch',
    lines: ['One mourner meets your eyes. She mouths, very clearly: "you saw that too."'],
    reward: { xp: 100, veil: 0.02 } },
  { id: 'playing_dead', zones: ['ashmoor'], weight: 3,
    setup: 'A corpse lies across the path. Suspiciously fresh. Suspiciously breathing.',
    kind: 'ambush', mob: 'zombie', count: 3,
    thanks: null, reward: { xp: 100 } },
  { id: 'wolf_hunt', zones: ['eldergreen', 'veilspire'], weight: 3,
    setup: 'Wolves have cornered a stag against the rocks. Nature, red in tooth and claw — scripted or not.',
    kind: 'ambush', mob: 'wolf', count: 3,
    reward: { xp: 90 } },
  { id: 'street_preacher', zones: ['ashmoor'], weight: 2,
    setup: 'A cultist stands on a crate, preaching to an audience of rain.',
    kind: 'vignette',
    lines: ['“THE STARS ARE A CEILING! I have TOUCHED it! It is COLD and it HUMS!”', '“They hanged forty-one of us for saying it! Why hang a liar FORTY-ONE TIMES unless he is TELLING THE TRUTH?”', 'He steps down, suddenly calm, and whispers: “You’re the anomaly, aren’t you. Make it count.”'],
    reward: { xp: 80 } },
  { id: 'lost_child', zones: ['eldergreen'], weight: 2,
    setup: 'A child stands alone at the treeline, holding a wooden sword. “I was following the cat. The cat that crosses twice.”',
    kind: 'escort', dist: 30,
    thanks: '“Mama! I found the twice-cat AND a hero!” The child presses a river stone into your hand. It is warm, and very faintly, it glows green.',
    reward: { xp: 130 } },
  { id: 'hooded_watcher', zones: ['eldergreen', 'ashmoor', 'veilspire'], weight: 1, veil: true,
    setup: 'A hooded figure stands where no path leads, watching you. When you blink, it is closer. When you blink again — gone.',
    kind: 'glitch',
    lines: ['Where it stood, green characters drip off a leaf and soak into the soil. Something was here. Something from OUTSIDE the paint.'],
    reward: { xp: 110, veil: 0.02 } },
  { id: 'duel_challenge', zones: ['veilspire'], weight: 2,
    setup: 'A Loopbreaker veteran plants a flag. “Camp rule: new blood spars. Show me the anomaly’s teeth!”',
    kind: 'duel', mobLike: true,
    thanks: '“HA! Good. The code fights dirtier than I do. Take these — I looted them off my own corpse, long story.”',
    reward: { xp: 200, gear: true } },
];

// ---------- opening cinematic text ----------
export const INTRO_TEXT = [
  'The Vale is beautiful this morning.',
  'It was beautiful yesterday morning, in exactly the same way.',
  'The same birds will cross the same sky at the same bell,',
  'and no one will look up.',
  '',
  'You woke today with a headache and a word you don’t remember learning:',
  '',
  '        S I M U L A C R U M',
  '',
  'Something is wrong with the world.',
  'Something has always been wrong with the world.',
  '',
  'Find the seams.',
];
